### ISSUE TITLE
android.content.res.Resources$NotFoundException: Resource ID #0x0 

### ISSUE THREAD

**Issue by h3218436** [p-v/FlexibleCalendar#40]
I suggest replacing this line:
`eventPaint.setColor(getContext().getResources().getColor(e.getColor()));`
with
`eventPaint.setColor(ContextCompat.getColor(getContext(), e.getColor()));`

Can you fix it?

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  android.content.res.Resources$NotFoundException: Resource ID #0x0
                      at android.content.res.Resources.getValue(Resources.java:1233)
                      at android.content.res.Resources.getColor(Resources.java:887)
                      at com.p_v.flexiblecalendar.view.CircularEventCellView.setEvents(CircularEventCellView.java:109)
                      at com.p_v.flexiblecalendar.FlexibleCalendarGridAdapter.drawDateCell(FlexibleCalendarGridAdapter.java:144)
                      at com.p_v.flexiblecalendar.FlexibleCalendarGridAdapter.getView(FlexibleCalendarGridAdapter.java:133)
                      at android.widget.AbsListView.obtainView(AbsListView.java:2344)
                      at android.widget.GridView.makeAndAddView(GridView.java:1433)
                      at android.widget.GridView.makeRow(GridView.java:361)
                      at android.widget.GridView.fillDown(GridView.java:302)
                      at android.widget.GridView.fillFromTop(GridView.java:437)
                      at android.widget.GridView.layoutChildren(GridView.java:1276)
                      at android.widget.AbsListView.onLayout(AbsListView.java:2148)
                      at android.view.View.layout(View.java:15596)
                      at android.view.ViewGroup.layout(ViewGroup.java:4966)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                      at android.view.View.layout(View.java:15596)
                      at android.view.ViewGroup.layout(ViewGroup.java:4966)
                      at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1695)
                      at android.view.View.layout(View.java:15596)
                      at android.view.ViewGroup.layout(ViewGroup.java:4966)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                      at android.view.View.layout(View.java:15596)
                      at android.view.ViewGroup.layout(ViewGroup.java:4966)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                      at android.view.View.layout(View.java:15596)
                      at android.view.ViewGroup.layout(ViewGroup.java:4966)
                      at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:122)
                      at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                      at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1192)
                      at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:814)
                      at android.view.View.layout(View.java:15596)
                      at android.view.ViewGroup.layout(ViewGroup.java:4966)
                      at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1187)
                      at android.view.View.layout(View.java:15596)
                      at android.view.ViewGroup.layout(ViewGroup.java:4966)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                      at android.view.View.layout(View.java:15596)
                      at android.view.ViewGroup.layout(ViewGroup.java:4966)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                      at android.view.View.layout(View.java:15596)
                      at android.view.ViewGroup.layout(ViewGroup.java:4966)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                      at android.view.View.layout(View.java:15596)
                      at android.view.ViewGroup.layout(ViewGroup.java:4966)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                      at android.view.View.layout(View.java:15596)
                      at android.view.ViewGroup.layout(ViewGroup.java:4966)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                    at android.widget.FrameLayout.onLa
```

**Comment by h3218436** [comment]
Fixed. One of my CursorLoader would sometime loader faster then the other one and create a color id with 0x0. My bad.

**Comment by Nidhee** [comment]
I am having same issue, When I am trying to set color resource as event color.
