### ISSUE TITLE
NPE when user clicks on date outside current month

### ISSUE THREAD

**Issue by ebabel** [p-v/FlexibleCalendar#54]
http://imgur.com/a/d6uKs
When clicking on the bottom "5" before clicking on a date within the current month, the following NPE occurs.
`java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.p_v.flexiblecalendar.entity.SelectedDateItem.equals(java.lang.Object)' on a null object reference
                                                                                     at com.p_v.flexiblecalendar.MonthViewPagerAdapter.refreshUserSelectedItem(MonthViewPagerAdapter.java:210)
                                                                                     at com.p_v.flexiblecalendar.FlexibleCalendarView$MonthChangeListener.onPageSelected(FlexibleCalendarView.java:326)
                                                                                     at android.support.v4.view.ViewPager.dispatchOnPageSelected(ViewPager.java:1939)
                                                                                     at android.support.v4.view.ViewPager.scrollToItem(ViewPager.java:687)
                                                                                     at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:671)
                                                                                     at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:632)
                                                                                     at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:624)
                                                                                     at com.antonyt.infiniteviewpager.InfiniteViewPager.setCurrentItem(InfiniteViewPager.java:48)`

**Comment by badadin** [comment]
Try to select some date after you initialized calendar view. Something like this:

```
Calendar calendar = Calendar.getInstance();
calendar.setTimeInMillis(new Date().getTime());

flexibleCalendarView.selectDate(calendar.get(Calendar.YEAR),
    calendar.get(Calendar.MONTH),
    calendar.get(Calendar.DAY_OF_MONTH));
```

**Comment by p-v** [comment]
Feel free to reopen if there is any confusion.
